config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'users', to: 'users#index', as: 'users_index'

  resources :foods, only: %i[index new create destroy]

  root 'foods#index'

  get 'recipes/shopping_list', to: 'recipes#shopping_list', as: 'shopping_list'

  resources :recipes, only: %i[index show new create destroy] do
    collection do
      get 'public_recipes'
    end
    member do
      get 'update_public'
    end
  end

  resources :recipe_foods, only: %i[new create edit destroy]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  # has_and_belongs_to_many :foods, join_table: 'recipe_foods'
  has_many :foods, through: :recipe_foods
  scope :public_recipes, -> { where(public: true).order(created_at: :desc) }

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true

  def total_foods_price
    prices = []

    foods.each do |food|
      recipe_food = RecipeFood.find_by(recipe_id: id, food_id: food.id)
      food_total = (recipe_food.quantity * food.price)
      puts '--------------------------------------'
      puts "recipe: #{name}, food: #{food.name}, quantity: #{recipe_food.quantity}, price: #{food.price}"
      prices.push(food_total)
    end
    prices.sum
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  def index
    @recipes_data = Recipe.all
    @user_owner = current_user.id
  end

  def public_recipes
    @public_recipes_data = Recipe.public_recipes.includes(:user, :foods)
  end

  def show
    @recipe_data = Recipe.includes(:recipe_foods).find(params[:id])
    @foods = @recipe_data.recipe_foods
    # includes(:recipe_foods).where(recipe_foods: { recipe_id: @recipe_data.id })
  end

  def new
    @user_owner = current_user
    @recipe = Recipe.new
  end

  def create
    @recipe_data = Recipe.new(recipe_params)
    @recipe_data.user_id = current_user.id

    if @recipe_data.public.nil?
      @recipe_data.public = false
      puts 'entro al if'
    end

    if @recipe_data.save
      flash[:notice] = 'The recipes was created successfully!'
    else
      flash[:alert] = 'The recipes was not created!'
    end
    redirect_to recipes_path
  end

  def edit; end

  def update_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: params[:public])
  end

  def destroy
    @recipe_destroy = Recipe.find(params[:id])
    if @recipe_destroy.destroy
      flash[:notice] = 'The recipes was deleted successfully!'
    else
      flash[:alert] = 'The recipes was not deleted!'
    end
    redirect_to recipes_path
  end

  def shopping_list
    @user = current_user
    @recipes = @user.recipes.includes(recipe_foods: :food) || [] # Añadido .includes(recipe_foods: :food)
    @stock_user = calculate_user_stock
    @foods_needed = calculate_foods_needed
    @foods_needed = sort_foods_needed(@foods_needed)
    @foods_to_buy = calculate_foods_to_buy(@foods_needed, @stock_user)
    @total_price = calculate_total_price
  end

  def sort_foods_needed(foods_needed)
    sort = params[:sort]
    case sort
    when 'food_name_asc'
      foods_needed.sort.to_h
    when 'food_name_desc'
      foods_needed.sort.reverse.to_h
    when 'price_asc'
      foods_needed.sort_by { |food_name, _| Food.obtener_precio(food_name) }.to_h
    when 'price_desc'
      foods_needed.sort_by { |food_name, _| Food.obtener_precio(food_name) }.reverse.to_h
    else
      foods_needed
    end
  end

  private

  def calculate_user_stock
    stock = {}
    @user.foods.each do |food|
      if stock.key?(food.name)
        stock[food.name] += food.quantity.to_i
      else
        stock[food.name] = food.quantity.to_i
      end
    end
    stock
  end

  def calculate_foods_needed
    foods_needed = {}
    @user.recipes.includes(recipe_foods: :food).each do |recipe|
      recipe.recipe_foods.each do |recipe_food|
        food = recipe_food.food
        next if recipe_food.quantity.blank?

        if foods_needed.key?(food.name)
          foods_needed[food.name] += recipe_food.quantity.to_i
        else
          foods_needed[food.name] = recipe_food.quantity.to_i
        end
      end
    end
    foods_needed
  end

  def calculate_foods_to_buy(foods_needed, stock_user)
    foods_to_buy = {}
    foods_needed.each do |k, v|
      quantity_missing = [0, v - (stock_user[k] || 0)].max
      foods_to_buy[k] = quantity_missing if quantity_missing.positive?
    end
    foods_to_buy
  end

  def calculate_total_price
    total_price = 0
    @foods_needed.each do |k, v|
      price = Food.obtener_precio(k)
      quantity_missing = [0, v - (@stock_user[k] || 0)].max
      total_price += quantity_missing * price
    end
    total_price
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def size_by_food(recipe)
    recipe.foods.count
  end

  def total_foods_by_recipe(user)
    return 0 if user.nil?

    food_names = []

    user.foods_all_recipes.each do |food|
      food_names << food.name
    end

    food_names.uniq.size
  end

  def total_foods_to_buy(foods_to_buy)
    return 0 if foods_to_buy.nil?

    foods_to_buy.size
  end
end

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/destroy.html.erb
<h1>Recipes#destroy</h1>
<p>Find me in app/views/recipes/destroy.html.erb</p>

app/views/recipes/edit.html.erb
<h1>Recipes#edit</h1>
<p>Find me in app/views/recipes/edit.html.erb</p>

app/views/recipes/index.html.erb
<div class="contRecipes">
    <h1>List of recipes</h1>

    <% @recipes_data.each do |item| %>
        <div class="recipe">
            <div class="title">
            <p> <%= link_to item.name, recipe_path(item.id), class: "newRecipeName"%> </p>
            <% if(@user_owner == item.user_id) %>
                <%= button_to "REMOVE", recipe_path(item.id), method: :delete %>
            <% end %>
            </div>
            <p> <%= item.description %> </p>
        </div>
    <% end %>

    <%= link_to "Add new recipe", new_recipe_path, class: "newRecipe" %>

</div>

app/views/recipes/new.html.erb
<div class="contNewRecipe">
<h1>New recipe</h1>
<h2>for <%= @user_owner.name %></h2>

<%= form_with(model: @recipe, url: recipes_path, method: :post) do |form| %>
    <div class="form">    
        <div class="form">
            <%= form.label :name, "Name" %>
            <%= form.text_field :name %>
        </div>
  
        <div class="form">
            <%= form.label :preparation_time, "Preparation" %>
            <%= form.text_field :preparation_time %>
        </div>

        <div class="form">
            <%= form.label :cooking, "Cooking"  %>
            <%= form.text_field :cooking_time %>
        </div>

        <div class="form">
            <%= form.label :description, "Description" %>
            <%= form.text_area :description %>
        </div>

        <div class="form">
            <%= form.label :public, id: "label" %>
            <div class="toggle-button">
                <%= form.check_box :public, {class: 'slider', id: 'toggle'}, true, false %>
                <label class="slider-label" for="toggle">
                <div class="circle"></div>
                </label>
            </div>
        </div>
  
        <div class="form">
            <%= form.submit 'Create Post', class: "FormButton" %>
        </div>
    </div>
  <% end %>

app/views/recipes/public_recipes.html.erb
<div class="container">
  <div class="inner-padding">
    <h1 class="header-public-recipe-list">Public Recipes</h1>
    <ul class="recipe-list">
      <% @public_recipes_data.each do |recipe| %>
        <li class="recipe-item">
          <div class="recipe-info">
            <div class="recipe-title"><%= link_to recipe.name, recipe_path(recipe) %></div>
            <div class="recipe-author">by <%= recipe.user.name %></div>
          </div>
          <div class="recipe-details">
            <p class="recipe-total-food-items">Total food items:<%= size_by_food(recipe) %> <!-- Itmes de comida (helper recipes) --></p>
            <p class="recipe-total-price">Total price: <%= recipe.total_foods_price %><!-- precio total --></p>
          </div>
        </li>
      <% end %>
    </ul>
  </div> 
</div>

app/views/recipes/shopping_list.html.erb
<h2>Shopping List</h2>
<div class="info-row">
<h4 class="info-item2">Amount of food items to buy: <%= total_foods_to_buy(@foods_to_buy) %></h4>
<h4 class="info-item1">Total value of food needed:  <%= @total_price %></h4>
</div>
<%# <%= @stock_user %> 
<%# <%= @foods_needed %> 

<table>
<thead>
    <tr>
      <th class="food-name">
        <div class="header-container">
          <span>Food</span>
          <div class="sorting-arrows">
            <%= link_to '', { sort: 'food_name_asc' }, class: 'triangle-up2' %> <!-- Ascending Order -->
            <%= link_to '', { sort: 'food_name_desc' }, class: 'triangle-down2' %> <!-- Descending Order -->
          </div>
        </div>
      </th>
      <th class="quantity">Quantity Missing</th>
      <th class="price">
        <div class="header-container">
          <span>Price</span>
          <div class="sorting-arrows">
            <%= link_to '', { sort: 'price_asc' }, class: 'triangle-up2' %> <!-- Ascending Order -->
            <%= link_to '', { sort: 'price_desc' }, class: 'triangle-down2' %> <!-- Descending Order -->
          </div>
        </div>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @foods_needed.each do |food_name, quantity_needed| %>
      <% quantity_missing = [0, quantity_needed - (@stock_user[food_name] || 0)].max %>
      <% next if quantity_missing == 0 %>
      <tr>
        <td class="food-name"><%= food_name %></td>
        <td class="quantity"><%= quantity_missing %></td>
        <td class="price">
          <% food_price = Food.obtener_precio(food_name) %>
          <% total_food_price = quantity_missing * food_price %>
          <%= total_food_price %>
        </td>
      </tr>
    <% end %>
</tbody>

</table>

app/views/recipes/show.html.erb
<div class="contRecipeDetails" id="contRecipeDetails">
    <h1>Recipe <%= @recipe_data.id %> - <%= @recipe_data.name %></h1>
    <h2>details</h2>

    <div class="contRecip1">
        <p>Preparation time: <%= @recipe_data.preparation_time %> hour</p>
        
        
        <div class="contToggleShow">
            <p>Public: <%= @recipe_data.public ? "Sí" : "No" %></p>
            <div class="toggle-button">
                <input type="checkbox" id="toggle1" class="slider" <%= @recipe_data.public ? 'checked' : '' %>>
                <label class="slider-label" for="toggle1">
                    <div class="circle"></div>
                </label>       
            </div>
        </div>
    </div>

    <p>Cooking time: <%= @recipe_data.cooking_time %> hours</p>
    
    <p><%= @recipe_data.description %></p>

    <div class="contRecip2">
        <%= link_to "Generate shopping list", shopping_list_path, class: "btnDetails"%>
        <%= link_to "Add ingredient", new_recipe_food_path(recipe_id: @recipe_data.id), class: "btnDetails"%>        
    </div>  
</div>

<div class="table">
    <table>
        <thead>
            <tr>
                <th>Food</th>
                <th>Quantity</th>
                <th>Value</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @foods.each do |item| %>
                <tr>
                    <td><%= item.food.name %></td>
                    <td><%= item.quantity %></td>
                    <td><%= item.quantity * item.food.price %></td>
                    <td class="actionsShow">
                        <%= link_to "Modify", class: "link to"%>
                        <%= "&nbsp;" "&nbsp;".html_safe %>
                        <%= button_to "Remove", recipe_food_path(item.id), method: :delete %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div> 

<script> 

checkbox = document.getElementById("toggle1");

checkbox.addEventListener("change", function() {
    const newValue = this.checked;

fetch("<%= update_public_recipe_path(@recipe_data.id) %>?public=" + newValue, {
      method: "GET",
      headers: {
        "X-CSRF-Token": "<%= form_authenticity_token %>",
      },
    });
  });  

</script> 

app/views/recipes/update.html.erb
<h1>Recipes#update</h1>
<p>Find me in app/views/recipes/update.html.erb</p>