config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'users', to: 'users#index', as: 'users_index'

  resources :foods, only: %i[index new create destroy]

  root 'foods#index'

  get 'recipes/shopping_list', to: 'recipes#shopping_list', as: 'shopping_list'

  resources :recipes, only: %i[index show new create destroy] do
    collection do
      get 'public_recipes'
    end
    member do
      get 'update_public'
    end
  end

  resources :recipe_foods, only: %i[new create edit destroy]
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods
  # has_and_belongs_to_many :foods, join_table: 'recipe_foods'

  scope :active, -> { where(is_deleted: false) }

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :quantity, presence: true, numericality: { greater_than: 0 }

  def self.obtener_precio(name)
    puts "Obteniendo precio para: #{name}"
    food = Food.find_by(name: name)
    price = food ? food.price : 0
    puts "Precio obtenido: #{price}"
    price
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food, only: %i[show edit update destroy]

  def index
    @foods = if params[:sort] == 'name'
               current_user.foods.where(is_deleted: false).order('LOWER(name)')
             else
               current_user.foods.where(is_deleted: false)
             end
  end

  def new
    @food = Food.new
  end

  def create
    formatted_name = format_food_name(food_params[:name])
    existing_food = current_user.foods.find_by(name: formatted_name)

    if existing_food
      update_existing_food(existing_food)
    else
      create_new_food(formatted_name)
    end
  end

  def destroy
    @food = Food.find(params[:id])
    if @food.update(is_deleted: true)
      flash[:notice] = 'Food was successfully "deleted".'
    else
      flash[:alert] = 'Failed to "delete" food!'
    end
    redirect_to foods_path
  end

  private

  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end

  def format_food_name(name)
    formatted_name = name.strip.downcase.titleize.singularize
    formatted_name.gsub(/\s+/, '')
  end

  def update_existing_food(existing_food)
    if existing_food.is_deleted
      reactivate_and_update_food(existing_food)
    else
      update_food_quantity_and_price(existing_food)
    end
    redirect_to foods_path, notice: 'Food quantity and price were successfully updated.'
  end

  def reactivate_and_update_food(food)
    food.update(
      is_deleted: false,
      quantity: food_params[:quantity].to_i,
      price: food_params[:price].to_f
    )
  end

  def update_food_quantity_and_price(food)
    new_quantity, avg_price = calculate_new_quantity_and_price(food)
    food.update(quantity: new_quantity, price: avg_price)
  end

  def calculate_new_quantity_and_price(food)
    new_quantity = food.quantity + food_params[:quantity].to_i
    total_cost_old = food.price * food.quantity
    total_cost_new = food_params[:price].to_f * food_params[:quantity].to_i
    total_cost = total_cost_old + total_cost_new
    avg_price = total_cost / new_quantity
    [new_quantity, avg_price]
  end

  def create_new_food(formatted_name)
    @food = current_user.foods.build(food_params.merge(name: formatted_name))
    if @food.save
      redirect_to foods_path, notice: 'Food was successfully created.'
    else
      render :new
    end
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/create.html.erb
<h1>Foods#create</h1>
<p>Find me in app/views/foods/create.html.erb</p>

app/views/foods/destroy.html.erb
<h1>Foods#destroy</h1>
<p>Find me in app/views/foods/destroy.html.erb</p>

app/views/foods/edit.html.erb
<h1>Foods#edit</h1>
<p>Find me in app/views/foods/edit.html.erb</p>

app/views/foods/index.html.erb
<div class="container food-container">
<%= link_to 'Add Food', new_food_path, class: "add-food-button" %>

<table>
  <thead>
    <tr>
      <th class="food-name">
          <div class="header-container">
            Name
            <%= link_to '', foods_path(sort: 'name'), class: 'triangle-up' %>
          </div>
        </th>
      <th class="measurement-unit">Measurement Unit</th>
      <th class="price">Unit Price</th>
      <th class="quantity">Quantity</th>
      <th class="actions">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td class="food-name"><%= food.name %></td>
        <td class="measurement-unit"><%= food.measurement_unit %></td>
        <td class="price">$<%= food.price %></td>
        <td class="quantity"><%= food.quantity %></td>
        <td class="actions">
            <%= button_to 'Delete', food, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button-link', id: "Delete_#{food.id}" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/foods/new.html.erb
<h1 class="index-title">Add New Food</h1>

<%= form_with(model: @food, local: true) do |form| %>

  <div class="field">
    <%= form.text_field :name, placeholder: "Food Name", autocomplete: "name", class: 'input-with-label' %>
  </div>
  <div class="field">
    <%= form.select :measurement_unit, options_for_select(['g', 'ml', 'unit']), {}, { class: 'input-with-label' } %>
  </div>
  <div class="field">
    <%= form.text_field :price, placeholder: "Price", class: 'input-with-label', step: 'any' %>
  </div>
  <div class="field">
    <%= form.text_field :quantity, placeholder: "Quantity", class: 'input-with-label', step: 'any' %>
  </div>
  <div class="actions">
    <%= form.submit "Add Food", class: 'post-form-button' %>
  </div>
<% end %>

app/views/foods/show.html.erb
<h1>Foods#show</h1>
<p>Find me in app/views/foods/show.html.erb</p>

app/views/foods/update.html.erb
<h1>Foods#update</h1>
<p>Find me in app/views/foods/update.html.erb</p>