config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'users', to: 'users#index', as: 'users_index'

  resources :foods, only: %i[index new create destroy]

  root 'foods#index'

  get 'recipes/shopping_list', to: 'recipes#shopping_list', as: 'shopping_list'

  resources :recipes, only: %i[index show new create destroy] do
    collection do
      get 'public_recipes'
    end
    member do
      get 'update_public'
    end
  end

  resources :recipe_foods, only: %i[new create edit destroy]
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :recipe_id, uniqueness: { scope: :food_id, message: 'Ingredient already exists in the recipe' }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def index; end

  def show; end

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @ingredients = Food.all
    @new_ingredient = RecipeFood.new
  end

  def create
    @new_ingredient = RecipeFood.new(recipe_food_params)
    if @new_ingredient.save
      flash[:notice] = 'The ingredient was added successfully!'
    else
      flash[:alert] = 'The ingredient was not added, check if alreade exist!'
    end
    redirect_to recipe_path(@new_ingredient.recipe_id)
  end

  def edit; end

  def update
    @ingredient = RecipeFood.find(params[:id])
    if @ingredient.update(recipe_food_params)
      flash[:notice] = 'The ingredient was updated successfully!'
    else
      flash[:alert] = 'The ingredient was not updated!'
    end
    redirect_to recipe_path(@ingredient.recipe_id)
  end

  def destroy
    @ingredient = RecipeFood.find(params[:id])
    if @ingredient.destroy
      flash[:notice] = 'The ingredient was deleted successfully!'
    else
      flash[:alert] = 'The ingredient was not deleted!'
    end
    redirect_to recipe_path(@ingredient.recipe_id)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity, :recipe_id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/create.html.erb
<h1>RecipeFoods#create</h1>
<p>Find me in app/views/recipe_foods/create.html.erb</p>

app/views/recipe_foods/destroy.html.erb
<h1>RecipeFoods#destroy</h1>
<p>Find me in app/views/recipe_foods/destroy.html.erb</p>

app/views/recipe_foods/edit.html.erb
<h1>RecipeFoods#edit</h1>
<p>Find me in app/views/recipe_foods/edit.html.erb</p>

app/views/recipe_foods/index.html.erb
<h1>RecipeFoods#index</h1>
<p>Find me in app/views/recipe_foods/index.html.erb</p>

app/views/recipe_foods/new.html.erb
<h1>Add new ingredient to recipe <%= @recipe.name %></h1>

<%= form_for @new_ingredient, url: recipe_foods_path, method: :post do |f| %>

    <%= f.hidden_field :recipe_id, value: @recipe.id %>

    <div class="form">
        <%= f.label :food_id %>
        <%= f.select :food_id, options_for_select(@ingredients.map { |p| [p.name, p.id] }), include_blank: 'Choose an ingredient' %>
    </div>
    
    <div class="form">
        <%= f.label :quantity %>
        <%= f.text_field :quantity %>
    </div>

    <%= f.submit "Guardar" %>

<% end %>

app/views/recipe_foods/show.html.erb
<h1>RecipeFoods#show</h1>
<p>Find me in app/views/recipe_foods/show.html.erb</p>

app/views/recipe_foods/update.html.erb
<h1>RecipeFoods#update</h1>
<p>Find me in app/views/recipe_foods/update.html.erb</p>