config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'users', to: 'users#index', as: 'users_index'

  resources :foods, only: %i[index new create destroy]

  root 'foods#index'

  get 'recipes/shopping_list', to: 'recipes#shopping_list', as: 'shopping_list'

  resources :recipes, only: %i[index show new create destroy] do
    collection do
      get 'public_recipes'
    end
    member do
      get 'update_public'
    end
  end

  resources :recipe_foods, only: %i[new create edit destroy]
end

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="navbar">
    <div class="navbar-left">
      <span>RecipeApp</span>
    </div>
    <div class="navbar-right">
      <ul class="navbar-items">
        <li><%= link_to "Foods", foods_path, class: "navbar-list-item" %></li>
        <li><%= link_to "Recipes", recipes_path, class: "navbar-list-item" %></li>
        <li><%= link_to "Public Recipes", public_recipes_recipes_path, class: "navbar-list-item" %></li>
        <li><%= link_to "Shopping List", shopping_list_path, class: "navbar-list-item" %></li>
      </ul>
    </div>
  </nav>
<% else %>
  <nav>

  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container center">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>